## Numpy Problems

## Beginner Problem

## Zero-Based 2D Array
### Create a $5 \times 5$ 2D NumPy array where all elements are zero, but the element at index $(2, 3)$ is set to 10. Then, print the array's shape and dimension

In [19]:
import numpy as np

z_array = np.zeros((5,5))

z_array[2,3] = 10

z_array

print(z_array.shape)
print(z_array.ndim)

(5, 5)
2


## Ranged Array Filtering
### Create a 1D NumPy array containing integers from 50 to 80 (inclusive). Use Boolean indexing to extract and print only the elements that are greater than 65.

In [46]:
ad_array = np.random.randint(50,80,size=15)

bool = ad_array > 65

print(ad_array)
print(bool)

[62 62 64 62 51 79 62 60 55 52 73 76 70 53 51]
[False False False False False  True False False False False  True  True
  True False False]


## Intermediate Problems

## Normalization using Broadcasting
### Create a $4 \times 3$ random integer array (e.g., values between 1 and 100). Use broadcasting (without explicit loops) to subtract the mean of each column from the elements in that column.

In [61]:
nor = np.random.randint(1,100,12).reshape(4,3)

col_mean = np.mean(nor,axis=0)

after_mean = nor-col_mean

print(after_mean)

[[ 36.75 -24.   -29.75]
 [  4.75  23.    -1.75]
 [-18.25 -15.    37.25]
 [-23.25  16.    -5.75]]


## Dot Product and Axis Sum
### Create two 1D arrays, $A$ and $B$, each with 5 random integers.Calculate the dot product of $A$ and $B$ using a NumPy function.Stack $A$ and $B$ vertically to create a $2 \times 5$ array $C$.Calculate the sum of all elements along Axis 1 (the rows) of array $C$

In [70]:
a_array = [1,2,3,4,5] 
b_array = [6,7,8,9,10]

dot_product = np.dot(a_array,b_array)

c_array =np.vstack((a_array,b_array))

sum_array = np.sum(c_array,axis=1)

print(c_array)
print(sum_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[15 40]


## Advanced Problems

## Conditional Element Replacement (Masking)
### Create a $6 \times 6$ array of random floating-point numbers between 0 and 1. Use advanced Boolean masking to replace all elements in the array that are less than 0.2 or greater than 0.8 with the value -1.

In [77]:
rand_array = np.random.rand(6,6)

bool_array = (rand_array < 0.2) | (rand_array > 0.8)

rand_array[bool_array] = -1

print(rand_array)

[[-1.         -1.          0.79166398 -1.          0.28643192  0.65201847]
 [-1.         -1.          0.51821088 -1.          0.57991555  0.78517355]
 [-1.         -1.          0.54514113  0.3349382  -1.          0.578439  ]
 [ 0.78449326  0.64414794  0.48160055 -1.          0.35659363 -1.        ]
 [ 0.34583326 -1.         -1.          0.76808152 -1.         -1.        ]
 [-1.         -1.          0.47588154  0.32734009  0.21789844  0.25803556]]


## Paddings and Stride Modification
### Use the np.pad() function to add a border of zeros of size 1 around D, creating a 5×5 array E.

### Then, using slicing with a step (stride), extract the elements in the odd rows and even columns (using 0-based indexing) of E.

In [86]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

E = np.pad(a, pad_width=1, mode='constant', constant_values=0)

extracted_ele = E[1::2, 0::2]

print("Original Array",a)
print("Padding Array",E)
print("Extracted Array",extracted_ele)

Original Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Padding Array [[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]
Extracted Array [[0 2 0]
 [0 8 0]]
